import {ApiResponse} from './apiResponseTypes';

export interface LoginParams {
  email: string;
  password: string;
}

// Generated by https://quicktype.io

export type LoginResponse = ApiResponse<LoginData>

export interface LoginData {
  access_token: string;
  token_type: string;
  user: Object;
  
}

export interface RegisterParams {
  nama: string;
  email: string;
  pass: string;
  repass: string;
}

export type RegisterResponse = ApiResponse<RegisterData>

export interface RegisterData {
  email: string;
}
